# Generated by Django 5.0.3 on 2024-04-29 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("healthcare_centre_name", models.CharField(max_length=255)),
                ("child_number", models.CharField(max_length=255)),
                ("child_name", models.CharField(max_length=255)),
                ("child_gender", models.CharField(max_length=255)),
                ("date_of_birth", models.CharField(max_length=255)),
                ("weight_at_birth", models.CharField(max_length=255)),
                ("length_at_birth", models.CharField(max_length=255)),
                ("place_of_birth", models.CharField(max_length=255)),
                ("maternal_health_worker", models.CharField(max_length=255)),
                ("child_residence", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Child_visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Tarehe", models.DateField()),
                ("Joto_la_Mwili", models.IntegerField()),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="child.child"
                    ),
                ),
            ],
        ),
    ]
