# Generated by Django 5.0.3 on 2024-06-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("child", "0002_alter_child_visit_height"),
    ]

    operations = [
        migrations.AddField(
            model_name="child_visit",
            name="child_name",
            field=models.CharField(default="chile", max_length=255),
            preserve_default=False,
        ),
    ]
