# Generated by Django 5.0.3 on 2024-06-06 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("child", "0003_child_visit_child_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation_visit_child",
            name="child",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="child.child"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consultation_visit_child",
            name="child_name",
            field=models.CharField(default="aaa", max_length=255),
            preserve_default=False,
        ),
    ]
