# Generated by Django 5.0.3 on 2024-04-24 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mother",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("healthcare_centre_name", models.CharField(max_length=255)),
                ("Mothers_name", models.CharField(max_length=255)),
                ("RegistrationNumber", models.IntegerField()),
                ("MosquitoNetVoucherNumber", models.IntegerField()),
                ("Mage", models.IntegerField()),
                ("MEducation", models.CharField(max_length=255)),
                ("Mwork", models.CharField(max_length=255)),
                ("Height", models.CharField(max_length=255)),
                ("Fathers_name", models.CharField(max_length=255)),
                ("Fage", models.IntegerField()),
                ("Feducation", models.CharField(max_length=255)),
                ("Fwork", models.CharField(max_length=255)),
                ("Village", models.CharField(max_length=255)),
                ("ChairpersonsName", models.CharField(max_length=255)),
                ("how_many_pregnancies", models.IntegerField()),
                ("Alive_children", models.IntegerField()),
                ("Miscarriages", models.CharField(max_length=255)),
                ("HowManyBirths", models.IntegerField()),
                ("Miscarriageage", models.CharField(max_length=255)),
                ("Miscarriage_year", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Tarehe", models.DateField()),
                ("Joto_la_Mwili", models.IntegerField()),
                ("Blood_Preasure_140_100_na_zaidi", models.IntegerField()),
                ("Hb_chini_ya_60", models.IntegerField()),
                ("PMTCT_Lishe_ya_mtoto", models.CharField(max_length=255)),
                ("Mtoto_ananyonya", models.CharField(max_length=255)),
                ("Maziwa_yanatoka", models.CharField(max_length=255)),
                (
                    "Ameanza_kunyonya_ndani_ya_saa_moja",
                    models.CharField(max_length=255),
                ),
                ("Chuchu_zina_vidonda", models.CharField(max_length=255)),
                ("Yamejaa_sana", models.CharField(max_length=255)),
                ("Yana_jipu", models.CharField(max_length=255)),
                ("Chunguza_unyonyeshaji_toa_ushauri", models.CharField(max_length=255)),
                ("Linanywea", models.CharField(max_length=255)),
                ("Maumivu_makali", models.CharField(max_length=255)),
                (
                    "Mother",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mother.mother"
                    ),
                ),
            ],
        ),
    ]
