# Generated by Django 5.0.3 on 2024-04-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mother", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mother",
            old_name="miscarrimother_age_mother_age",
            new_name="miscarriage_age",
        ),
        migrations.RenameField(
            model_name="mother",
            old_name="miscarrimother_age_year",
            new_name="miscarriage_year",
        ),
        migrations.RenameField(
            model_name="mother",
            old_name="miscarrimother_ages",
            new_name="miscarriages",
        ),
    ]
