# Generated by Django 5.0.3 on 2024-06-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mother", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mother_visit",
            name="mother_name",
            field=models.CharField(default="mom", max_length=255),
            preserve_default=False,
        ),
    ]
