# Generated by Django 5.0.3 on 2024-04-24 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mother", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Visit",
            new_name="Mother_visit",
        ),
    ]
