# Generated by Django 5.0.3 on 2024-06-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mother", "0002_mother_visit_mother_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mother_visit",
            name="visit_number",
            field=models.CharField(max_length=255),
        ),
    ]
