# Generated by Django 5.0.3 on 2024-05-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_user_name_healthcareworker_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthcareworker",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
